apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:anoaCE5RpY/TuTwIJMe8rJmwxp+FqgmAPWLHB6ZUVJ78DLH5hK1jsQ==,iv:Wawggadgcr/I867Mg9ojuZ6uh7cXNc7mhF772mdnSCw=,tag:fh6Vq9ZZDS7nNYhQOO9KSw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1anxw7yvu9dn6a7dcl0z8vg8zw53362g0raevxxh6zqta7jzzjp0qse4xak
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByWk05ZU5Hdk00VzhIeGd2
            T0hWU21OUTZhWUtSaFo3SnZLRVZIOGtuOXdJCkFMQUpSb0RqUjdnbExRNlpxQ0sw
            OGQ4TWp5bWlYK1FVbHZWTndReXJsb0EKLS0tIFZXNWkxcjlrTkYrU20rV21WVlRz
            MnRidTQrYktyejFMdXVlT3NNdngwTTgKKxLZCrVvIAZ3IVGasGvewZTTNGM2VElB
            /qFaW9cO+zIxb0GMyJ90l+CtThyj+kBcwZVPae+MBNsufMvLKyEiRA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-09T11:04:40Z"
    mac: ENC[AES256_GCM,data:nzKWlMyksYQ7YP2DcKXn7/BKtVSIp0Maob2+93v46fO/2jgGnymOOqnBBBYYB7g2fE1O0z7aV7J5PzIbsKvIs1B/gECi7UtA22LBlmwxn12txdSlN2wugZOtBlG6uK7q3UDfbRb4o0Ly2+oPcTaWdtdnkOp3D+johzN3JSxExJA=,iv:zyG6lJgwYeZoDG5ZnY8B8jJ9rXXikzI3ashEiBY79dc=,tag:/cpCEoJ9ZNk1i8z7cOOcgw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
