apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:YrnKeclXTtRJQd6seU8=,iv:OgabN7FSGl8KGq5c5x6GYKMuCMVX+NMxS2PKNrCxOAs=,tag:0bosVqWKFpqmfbkwfL4k4Q==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:PT2o7VCAroppfR5ux/VkpXn1FCTyhY7YqA==,iv:JRimOvyeehqBaDlcdrEhI0wJmV9lebX019xsKit7SUo=,tag:JsjiQuEPe1N4J3eyXeYB5g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1anxw7yvu9dn6a7dcl0z8vg8zw53362g0raevxxh6zqta7jzzjp0qse4xak
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByNGRrRTVad1Rndm5MV3E5
            cnViN1FDSGhaRGNNZmF5c0tza1RKLys5YnowCnhWUHJITmRLTnVRWGZnRENST1Vw
            cEVsMmhpeTh6N0lXRXF1bmdYU2Q1b0EKLS0tIE9ROTUxQ1dmVzZvaXZaWkVyeFNl
            SUdKdUFzcnlhcWlDeHVSUzcrY2Y2RUEKW93BAmyZT29kMHTdLujL9J5T4IV3M56f
            cOQGPI8dN9CHsvm442FziTToq2nJvbMmJZKs4EKFRCjg0MGiTYKzlA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-07T21:01:22Z"
    mac: ENC[AES256_GCM,data:61pJIbggbJikc6VlpXsnHdCbYBj1y/tRrn21H5HHYdcOWGnAAJtsmZNLdjC+jiryy+lVAyAo2d9B809a7DOS62Jc56ZCW17+IImlZuTxYmU7PF0ykJDZ85OVYkJuF3UjMubZsOCXtqXvkJRFZH556/LE4Vp1LeovgzNvb2iiAiM=,iv:NzlXMDPhgmrnIBRHDSbxr/Q9/r8nxdOtz2xd6Ns780c=,tag:6UeCkUC4DvIFfcZydV95eA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
